#! /usr/bin/bash

source /etc/matrix-sendmail/config.env

MSM_LIB_DIR=/var/lib/matrix-sendmail
for f in $(find $MSM_SPOOL_DIR/system/new -type f)
do
  matrix-commander -c $MSM_LIB_DIR/credentials.json -s $MSM_LIB_DIR/store
  ret=$?
  
  if [ $ret -eq 0 ]
  then
    rm $f
  fi
done
